version: "3"

services:
  gateway:
    build: ./gateway
    command:
      - --spring.config.location=/opt/application.yaml
      - --server.port=9080
    volumes:
      - ./config/spring/application.yml:/opt/application.yaml:ro
    ports:
      - "9080:9080"
  catalog:
    build: ./catalog
    environment:
      APP_PRICING_ENDPOINT: http://gateway:9080/prices
      APP_STOCKS_ENDPOINT: http://gateway:9080/stocks
      APP_REFERER: http://catalog.me
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres?currentSchema=catalog
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
    depends_on:
      - pricing
      - stocks
      - postgres
  pricing:
    build: ./pricing
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres?currentSchema=pricing
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
    depends_on:
      - postgres
  stocks:
    build: ./stocks
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres?currentSchema=stocks
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d:ro
  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:9.5.2
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
